baseURL = 'https://sunny-hummingbird-989833.netlify.app//'
languageCode = 'es'
title = 'eliastello.ar'

preserveTaxonomyNames = true
removePathAccents = true
paginate = 5

[params]
	css = ["css/style.css"]

[taxonomies]
	tag = 'tags'
